spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jackson:
    mapper:
      accept_case_insensitive_properties: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
